#+TITLE: Miscellaneous or unprocessed links
* [2020-03-24] H+Pedia                              :transhumanism:
https://hpluspedia.org/wiki/Main_Page

* [2020-03-24] Don’t bail out the cruise industry | Hacker News
https://news.ycombinator.com/item?id=22672392

* [2020-03-24] Wilfred/helpful: A better Emacs *help* buffer
https://github.com/Wilfred/helpful

* [2020-03-26] EMDR Therapy (Eye Movement Desensitization & Reprocessing)
https://www.webmd.com/mental-health/emdr-what-is-it#1
Comment:
try it off youtube?
* [2020-03-26] michael_nielsen on Twitter: "@eriktorenberg @glenweyl Empirically, it's not really correct. The most unusual people I know are mostly extreme loners; a smaller minority are mostly at the other end of being extremely social, but with an intense capacity to be alone. Grothendieck said it quite well: https://t.co/bVmbbO7RIb" / Twitter
https://twitter.com/michael_nielsen/status/1220538523603763200
Selection:
Empirically, it's not really correct. The most unusual people I know are mostly extreme loners; a smaller minority are mostly at the other end of being extremely social, but with an intense capacity to be alone. Grothendieck said it quite well:
* [2020-03-31] Kill the newsletter: Convert newsletters into RSS feeds | Hacker News
https://news.ycombinator.com/item?id=12949154

* [2020-04-01] You are my spirit animal. I just got a polar/readwise/orgmode/Anki setup togeth... | Hacker News :remarkable:
https://news.ycombinator.com/item?id=22608287
Selection:
You are my spirit animal.

I just got a polar/readwise/orgmode/Anki setup together and I'd love to use this.
* [2020-04-01] Jitsi Meet: An open source alternative to Zoom | Hacker News
https://news.ycombinator.com/item?id=22669968
* [2020-04-02] Is there something like this for math? Does anyone know? | Hacker News
https://news.ycombinator.com/item?id=16373386
Comment:
like physics travel guide, but for math


* TODO todos
** TODO [2020-04-03] maybe sort by priority/date on export? or specify sort order in properties
* [[https://twitter.com/i/web/status/584492360349913088][TW]] at [2015-04-04] Когда я читаю в release notes софтины "various style and layout fixes", автоматически предполагаю что выпилили полезные настройки. :ttweet:
* TODO [2019-12-29] LOOPY: a tool for thinking in systems      :gr:
https://ncase.me/loopy/
* TODO [2020-01-01] pavelfatin/toyide: Modern IDE plus custom programming languages with interpreters and compilers :gr:
https://github.com/pavelfatin/toyide

* [2020-01-16] Running Lisp in Production                      :gr:
https://tech.grammarly.com/blog/running-lisp-in-production
* [2020-02-16] Elastic tabstops - a better way to indent and align code
http://nickgravgaard.com/elastic-tabstops/

* [2020-02-19] Open Source Design                          :graspw:
https://opensourcedesign.net/

* [2020-02-19] Can make syncthing only use LAN connection for some folders? - Support - Syncthing Forum :grasp:
https://forum.syncthing.net/t/can-make-syncthing-only-use-lan-connection-for-some-folders/7523/4
: I have few places (LANs) with “desktop server” in them, those servers sync everything using one syncthing instance (global discovery + relays as well).
: And then I have a mobile unit: One syncthing instance that syncs constantly only a handful of crucial folders (via LAN and Internet). Second syncthing instance that syncs all “non-critical + huge-sized” folders that has only local discovery on, hence will only sync when i’m on the same LAN with one of the “desktop servers”.
* [2020-02-16] VGraupera/1on1-questions: Mega list of 1 on 1 meeting questions compiled from a variety to sources
https://github.com/VGraupera/1on1-questions

* [2020-02-16] Kurzgesagt – In a Nutshell is creating Science Animation Videos | Patreon :donate:
https://www.patreon.com/Kurzgesagt

* [2020-01-09] Canop/broot: A new way to see and navigate directory trees :gr:
https://github.com/Canop/broot

* [2020-01-20] BusyBox cron container example                  :gr:
https://gist.github.com/andyshinn/3ae01fa13cb64c9d36e7
Selection:
Try crond --help:
* [2020-01-18] chakravala/Grassmann.jl: ⟨Leibniz-Grassmann-Clifford⟩ differential geometric algebra / multivector simplicial complex :gr:
https://github.com/chakravala/Grassmann.jl
Selection:
The Grassmann.jl package provides tools for doing computations based on multi-linear algebra, differential geometry, and spin groups using the extended tensor algebra known as Leibniz-Grassmann-Clifford-Hestenes geometric algebra.
* Tweet from @TheMagic_Ian
https://twitter.com/TheMagic_Ian/status/1245580360743710721

@TheMagic_Ian: Stop using fake-secure, or insecure video conferencing apps like Zoom, Skype, Duo, HouseParty,  Facebook Messenger, Slack, Teams! Consider #Jitsi or #Matrix clients like #Riot. twitter.com/theintercept/statu...
* doesn't look active. all top results are from 2017            :axol:upspin:
* [2020-04-06] (HN discussion on configs) wow, people have such strong opinions about software architecture, what it *should* be and what it *shouldn't be* etc
Like, unconditionally assuming that there is data and there is code, and that there is no middle ground whatsoever
often assuming there is one single way of doing things and that's it. incredible
* [2020-04-05] Start all of your commands with a comma (2009) | Hacker News
https://news.ycombinator.com/item?id=22778988
* [2020-04-08] Watch the Life Cycle of HIV in Colorful New Detail - Scientific American Blog Network
https://blogs.scientificamerican.com/observations/watch-the-life-cycle-of-hiv-in-colorful-new-detail/
* [2020-04-10] Emily Levesque Public Lecture: The Weirdest Stars in the Universe - YouTube
https://www.youtube.com/watch?v=YR-l0b2iYy0
Comment:
pretty cool talk!
* TODO [2020-03-24] PEP 593 -- Flexible function and variable annotations | Python.org
https://www.python.org/dev/peps/pep-0593/
* [2020-04-07] Firefox 75 for developers - Mozilla | MDN
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/75
Selection:
In the inspector, you can now use XPath expressions to locate elements, in addition to locating elements using CSS selectors as before (bug 963933).
* [2020-04-08] antonmedv/codejar: An embeddable code editor for the browser 🍯
https://github.com/antonmedv/codejar
Selection:
CodeJar honey_pot can be used via modules:

: <script type="module">
:   import {CodeJar} from 'https://medv.io/codejar/codejar.js'
: </script>
* TODO [2019-08-24] Simple dependent types in Python - DEV Community 👩‍💻👨‍💻 :gr:python:
https://dev.to/wemake-services/simple-dependent-types-in-python-4e14
Selection:
Now, we are going to combine our new knowledge about Literal and @overload together to solve our problem with open. At last!
* TODO [2019-08-18] JStumpp/awesome-android: A curated list of awesome Android packages and resources. :gr:
https://github.com/JStumpp/awesome-android#readme
Selection:
Development Alternatives
