#+TITLE: Orger
#+filetags: orger

* STRT [#C] feedbin?                                        :promnesia:orger:
** [2019-04-23] feedbin/feedbin-api: Feedbin API Documentation :grasp:

https://github.com/feedbin/feedbin-api#readme
: The base URL for all requests is https://api.feedbin.com/v2/ Only https is supported.
: The Feedbin API uses HTTP Basic authentication
: curl -u 'example@example.com:password' https://api.feedbin.com/v2/subscriptions.json


* TODO feels more and more that they should be a single tool :promnesia:orger:
* TODO youtube -- could mark as deleted if link = title?              :orger:
* TODO example of adding materialistic module -- literally matter of two commits? :blog:orger:
* TODO mirror emails to people only? e.g. some reasonable cutoff to exclude notifications etc? :orger:hpi:
* TODO [2020-03-24] lobste.rs/s/r9oskz.json                 :orger:
https://lobste.rs/saved.json
Comment:
port saved lobsters posts?
* TODO need to rename reddit module to reddit2org?                    :orger:
* [2020-03-22] Reddit's Save Functionality Sucks | My Random Thoughts by Cedric Amaya :reddit:exports:
https://cedric.tech/blog/reddits-save-functionality-sucks/
Selection:
For those unaware, saving things on Reddit as a non-Premium member works in the following way:

    limited to 1000 saved things (posts and comments) total; once the limit is reached, older things are replaced and essentially deleted from history
    saves are stored in reverse chronological order (latest to oldest)
    no way whatsoever to filter or sort saved content
    no searching capability is provided
    pagination limit on Reddit site is limited to 25 items, thus requiring users to use the “Next Page” or “Prev Page” buttons a lot
Comment:
the fuck?? they are deleted from history??
