#+TITLE: Intro
#+logseq_graph: false
#+filetags: exobrain

Exobrain, or "second brain", or "brain dump" is something like public wiki where you can keep your *bookmarks, notes, ideas and thoughts*.
Other people can search in your exobrain without having to physically interact with you.
The point is not to avoid physical interaction altogether, but to scale collaboration and knowledge exchange with other people.

It also allows for quicker iteration in writing blog posts or developing thoughts -- I can just quickly publish it here, share it gradually, and receive immediate feedback.

You can find org-mode sources of the files [[https://github.com/karlicoss/exobrain][here]], and the code to process and compile it [[https://github.com/karlicoss/exobrain-compiler][here]].

My exobrain contains semi-curated notes, tasks and links.

You can read more about exobrain on [[file:projects/exobrain.org][on its project page]].

* How to interact with exobrain?
:PROPERTIES:
:ID:       hwtntrctwthxbrn
:END:
Granted, there is lots of stuff here, and it's unclear what should you start with (if at all?).

** navigation sidebar
:PROPERTIES:
:ID:       nvgtnsdbr
:END:
It might be useful to explore and overview what's in my exobrain.
I'm still figuring out a system to distinguish 'link dump' pages for more interesting ones.
For now I'm just marking the latter with emojis, like this ⭐.

** search
:PROPERTIES:
:ID:       srch
:END:
I imagine [[file:index.html::#sidebar][*search*]] as the *primary* means of interacting with the exobrain.
The search yields you *results as you type*, which means incredibly fast feedback.

Note that at the moment it's still in development.

** via the source code?
:PROPERTIES:
:ID:       vthsrccd
:END:
You can also clone [[https://github.com/karlicoss/exobrain][the org-mode repository]] and eplore it in emacs directly.

** content
:PROPERTIES:
:ID:       cntnt
:END:
Some pages are quite unprocessed, but hopefully enough to make sense, especially if you are looking for something specific.
Note that not everything is my own text:
: some (if not most?) notes are just clippings
: Usually the clippings are quoted like this.

, so hopefully it's easy to tell apart what's quoted and what are my own thoughts.
If it's a clipping, doesn't mean I agree with it, or think the information is true, just means that I found it curious or worthy further research.

** page structure
:PROPERTIES:
:ID:       pgstrctr
:END:
Usually the content on the top of the page is somewhat curated and has higher information weight.
In the bottom of the page the links I've refiled pile up, and it's a bit more chaotic.
Usually I separate the two with ~============================~.

For example, see [[file:programming/python/python.org][page on python]].

** what do timestamps/priorities/todo states mean?
:PROPERTIES:
:ID:       whtdtmstmpsprrtstdsttsmn
:END:
First, if they annoy you, can turn toggle them via the settings in the bottom of the page.

- timestamps usually correspond to the time I created a bookmark/note, it's useful to assess how relevant is information (e.g. something from 5 years ago is more likely to be irrelevant to me now than something I added yesterday)
- priorities roughly mean how important/valuable I think a piece of information/todo is, for me or other people.
  Some bookmarks don't have priorities, which usually means I either haven't processed them yet.
- todo states (TODO/STRT/DONE) usually mean whether I've processed a bit of information, or it's in my queue

** longevity
:PROPERTIES:
:ID:       lngvty
:END:
While I'm generally doing my best to combat link rot, notes may move around, some IDs change, etc.
So if you see a piece of useful information here, make sure to copy its text, not just the heading link.

* FAQ
:PROPERTIES:
:CUSTOM_ID: faq
:END:
- do you really think that what you have here is interesting to anyone
  Yes, to some people. It's also useful to me when I want to share something I've already written down with other people.
- isn't it too much information?
  Yes, I have a certain kind of FOMO. But I think I'm managing it relatively well :)
- are you actually retaining any knowledge?
  Yes, in fact I can't imagine learning without notetaking.
  I certainly don't retail all of it (or perhaps even most of it).
  But even knowing where you can find some information in the form you like is a big part of learning process.
- aren't you making yourself vulnerable by sharing too much unfiltered content?
  I don't know... maybe? This is kind of inevitable with any form of public online communication.
  I do have beliefs/opinions from several years ago I'm not holding anymore or even cringe at.
  If you think something I have here is problematic etc., please feel free to reach out, and I'll be happy to discuss, I realy am open for change.


* Exobrains/wikis made by other people
:PROPERTIES:
:ID:       xbrnswksmdbythrppl
:END:
You can also find more links [[file:project/exobrain.org::#other][here]].

- [[https://wiki.nikitavoloboev.xyz]['Everything I know']] wiki by Nikita Voloboev

  If you want to check out one exobrain, start with this. It was my main inspiration and got lots of high quality and curated stuff.

- [[https://wiki.xxiivv.com/site/about.html][xxiivv]] by Devine Lu Linvega
- [[https://philosopher.life/#h0p3][h0p3's Wiki]]
- [[https://braindump.jethro.dev][Braindump]] by Jethro Kuan
- [[https://samsquire.github.io/ideas]['One Hundred Ideas for Computing']] repository by Sam Squire
- [[https://wiki.nikitavoloboev.xyz/other/wiki-workflow#similar-wikis-i-liked][more wiki examples]] from Nikita Voloboev
