#+TITLE: 
#+logseq_graph: false
#+filetags: biology

* [#B] [2017-11-30] protein folding                              :complexity:
:PROPERTIES:
:ID:       thprtnfldng
:END:
given a chain of amino acids, can you predict how is it going to fold?
ideally, folding should end up in the minimal energy state. if it doesn't you end up with prions?
in general, folding is an NP complete problem, are our body cells actually solving them somehow?
conjecture: evolution wouldn't actually use hard instances of protein folding, only computationally easy ones.
* [2017-05-15] [[http://en.wikipedia.org/wiki/Ethanol_fermentation][Fermentation]]
:PROPERTIES:
:ID:       mnnwkpdrgwkthnlfrmnttnfrmnttn
:END:
yeast anaerobic -> alcohol
muscle anaerobic -> lactic acid

: Fermentation is a metabolic process that converts sugar to acids, gases, and/or alcohol.

F: ermentation takes place in the lack of oxygen (when the electron transport chain is unusable) and becomes the cell’s primary means of ATP (energy) production.[1] It turns NADHand pyruvate produced in the glycolysis step into NAD+ and various small molecules depending on the type of fermentation (see examples below). In the presence of O2, NADH and pyruvate are used to generate ATP in respiration. This is called oxidative phosphorylation, and it generates much more ATP than glycolysis alone. For that reason, cells generally benefit from avoiding fermentation when oxygen is available. Exceptions include obligate anaerobes, which cannot tolerate oxygen.

https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5

: Пируваты (соли пировиноградной кислоты) — важные химические соединения в биохимии. Они являются конечным продуктом метаболизма глюкозы в процессегликолиза. Одна молекула глюкозы превращается при этом в две молекулы пировиноградной кислоты. Дальнейший метаболизм пировиноградной кислоты возможен двумя путями — аэробным и анаэробным.


* related                                                             :study:
:PROPERTIES:
:ID:       rltd
:END:
* [2020-12-26] [[https://news.ycombinator.com/item?id=25538820][Reverse Engineering the Source Code of the BioNTech/Pfizer SARS-CoV-2 Vaccine | Hacker News]]
:PROPERTIES:
:ID:       stsnwsycmbntrcmtmdrvrsngnbntchpfzrsrscvvccnhckrnws
:END:
: Synthetic Biology: A Primer
: 
: Wetware: A Computer in Every Living Cell
* TODO [#D] there have only been maybe {~10^40} organisms in earth’s history :drill:biology:
:PROPERTIES:
:CREATED:  [2019-09-18]
:ID:       6d460198-82c2-4fe7-9766-aded22b1e81e
:END:
from [[https://www.instapaper.com/read/1234260607/11339250][ip]]   [[https://www.scottaaronson.com/blog/?p=4253][Shtetl-Optimized » Blog Archive » On two blog posts of Jerry Coyne]]
