#+TITLE: Uncategorized
#+logseq_graph: false

* [2016-10-19] frequentist vs bayesian                          :probability:
:PROPERTIES:
:ID:       ead7fbccada57a4715493e6b07013e95
:END:
frequentist probability: relative frequencies
Bayesian probability: degree of knowledge

* [2016-02-28] Riemann surfaces                                     :complan:
:PROPERTIES:
:ID:       198c717b99077a8a2a79863ec273ba37
:END:
Alternatively one can think of Riemann sheets whereby on crossing a branch cut
one moves onto a different Riemann sheet of the function; the number of branches equals
the number of Riemann sheets. This allows closed contours to be formed by going around
branch cuts as many times as required to get back to the original Riemann sheet. However
although this scheme is very elegant, for calculational purposes it is best to treat branch
cuts as barriers one cannot cross.

* [2015-01-27] Elliptic vs Hyperbolic equations
:PROPERTIES:
:ID:       8932b56f-d110-463d-b071-fceeb2165c48
:END:
** Elliptic equations: well-posed BVP
:PROPERTIES:
:ID:       29ced0dc348874aafb3437f5fcbe87d7
:END:
*** TODO [2019-07-18] eh? what would be a practical example
:PROPERTIES:
:ID:       39a71c7d312dadb946aace3a70a7eb47
:END:
** Hyperbolic: well-posed IVP. E.g. wave equation
:PROPERTIES:
:ID:       0300ce2f2ac7a3c1237e4570694c12f2
:END:

* intuition about harmonic function https://math.stackexchange.com/questions/751293/intuitive-significance-of-harmonicity/751459 :physics:
:PROPERTIES:
:ID:       86e7a00262c7b7be529816a3e71d385f
:END:
A harmonic function is a function whose value at a point is always equal to the average of its values on a sphere centered at that point (reference). This is why they show up as steady-state solutions to the heat equation: if this averaging property weren't true, then heat would be flowing either from or to a point.

** TODO You might be interested in reading Needham's Visual Complex Analysis. :read:
:PROPERTIES:
:ID:       994791abe17140427167f69c64e6f3e7
:END:
* [#B] [2018-09-03] tensor space (product)                           :tensor:
:PROPERTIES:
:ID:       818f9b240684a00d0188664758949d8a
:END:
In mathematics, the tensor product V ⊗ W of two vector spaces V and W (over the same field) is itself a vector space, together with an operation of bilinear composition, denoted by ⊗, from ordered pairs in the Cartesian product V × W into V ⊗ W, in a way that generalizes the outer product. The tensor product of V and W is the vector space generated by the symbols v ⊗ w, with v ∈ V and w ∈ W, in which the relations of bilinearity are imposed for the product operation ⊗, and no other relations are assumed to hold.

https://jeremykun.com/2014/01/17/how-to-conquer-tensorphobia/
basically, (a, b) (x) (c, d) is a completely different element unless a is a multiple of c or b is a multiple of d
that's the difference from adiition where (a, b) + (c, d) would be (a + c, b + d)


* [2016-06-20] continuity intuition                                :topology:
:PROPERTIES:
:ID:       fc1e4be22f02d70619a65865b2f49c67
:END:
Consider the statement "a continuous function preserves closeness". That means if f ( x ) f(x) and f ( y ) f(y) are close to each other then x x and y y were close to each other originally.

In analysis, a function is continuous if you can make the image in the codomain as small as you like, by choosing a small enough part of the domain.

** https://math.stackexchange.com/questions/15963/what-is-the-intuition-for-the-point-set-topology-definition-of-continuity
:PROPERTIES:
:ID:       5a38912889a12efc818ba563002fb164
:END:
Instead, in metric spaces, I think of a function as continuous if it preserves limits, which can be intuitively (and generalizably) be phrased by saying that f is continuous if and only if whenever x is in the closure of a set A, then f(x) is in the closure of the set f(A).

** why the reverse doesn't work?
:PROPERTIES:
:ID:       6d72b3e462da426ab26a374abfe38f05
:END:
** topology as set of rulers https://mathoverflow.net/a/19156
:PROPERTIES:
:ID:       dd4de897b3f22a804d9509fe013ae9e4
:END:
This analogy is a backport from computer science back to geometry, and a bit was lost in the translation. In CS, for open, read "verifiable", and for closed, read "non-verifiable". Termination of blackbox programs is a verifiable property: if someone gives you a program and tells you it halts, then if they're telling the truth, if you wait you'll eventually see the machine stop and know they told you the truth. Nontermination is non-verifiable: no matter how long we wait, we can never be sure that the program won't halt soon, and so we can't verify we were told the truth. –

** https://mathoverflow.net/a/19173
:PROPERTIES:
:ID:       595354b328538476863ae2266729c4f6
:END:
mm. ok, function is continuous at p iff p in cl(A) means f(p) in cl(f(A)). okay that does make way more sense
*** [2018-10-15]  https://en.wikipedia.org/wiki/Kuratowski_closure_axioms
:PROPERTIES:
:ID:       8d6afc18befeb6be896d82de46f01bf5
:END:


* [2019-01-26] topological spaces intuition                        :topology:
:PROPERTIES:
:ID:       223ce35b285b3927a59cda8ce33cb7c4
:END:
hmm interesting definition in terms of 'touches' (v)
** in terms of closeness https://mathoverflow.net/a/19173/29889
:PROPERTIES:
:ID:       865052345ef0e613b483b37ced963b08
:END:
- No point touches the empty subset.
- If x is an element of A, then x touches A.
- If x touches A∪B, then x touches A or x touches B.
- If x touches A, and every element of A touches B, then x touches B.
then,
- continuity at point: forall A. x v A => f(x) v f(A)
  e.g. f(x) = sign(x). If we take x = 0 and A = (0, 1). In usual topology, 0 touches A, so f(0) = 0 should touch {1}. But it doesn't!
- X is connected iff every continuous function from x to {0, 1} is constant
  e.g. take two sets A, B. if you define f(A) = 0 and f(B) = 1 that's ok since B has no points near A and vice versa
  from nearness a better approach to continuity
- disconnected: if A∪B = X, A not v B and B not v A
- The sequence (xn) converges to the point x if x touches every subsequence of (xn).
- The topological space X is Hausdorff if for any two distinct points w,x∈X, there is a subset A of X such that w doesn't touch A and x doesn't touch the complement of A.
  dunno, this one is weird
  TODO shit, I really want the ability to insert todos wherever I want, not only on outline levels
*** START drill this?
:PROPERTIES:
:ID:       7f28803597ba177677eadadedcd29ee1
:END:
*** TODO compactness??
:PROPERTIES:
:ID:       626a101a32c6f93090eff0149e73db03
:END:
*** TODO open set: if no point touches its complement? e.g. with (0, 1) for any specific point we will find interval that separates from [-inf, 0] U [1, inf]
:PROPERTIES:
:ID:       0d629daa35424725e10637c611869dd0
:END:
and in reverse: x touches X if for all O in tau contaning x, U intersect X is not empty. ah shit makes sense.

if there is a continuous map to Sierpinski space?
    sierpinski space: topologically, {}, {top}, {top, bot}. so, bot v {top} but not in reverse
    this is also simplest example for non-symmetry I guess
    ugh. this is crap.
https://math.stackexchange.com/questions/31859/what-concept-does-an-open-set-axiomatise
Note that the above description really brings out the special role of the Sierpinski space S. Indeed, a subset of a topological space X is open precisely when the indicator function X→S is continuous.
*** [2019-01-26] right, I spent more than an hour proving something that could not be proved.. (that 0 touches (0, 1)). It really doesn't e.g. in discrete topology
:PROPERTIES:
:ID:       322af2974461a24dcc6c1082f095ab5b
:END:
**** TODO what can we learn from it?
:PROPERTIES:
:ID:       1e63e243e5c4289d85f725051b90693f
:END:
not sure...
** in terms of computability
:PROPERTIES:
:ID:       69740db9269fd2d687c13a07bbd9e4c4
:END:
'observable' sets are open in the topology
S = {T, bot}


** continuity    in terms of 'touches' relation: [ forall A. x v A => f(x) v f(A)  ]
:PROPERTIES:
:ID:       b9474d95-97ba-42b8-8d8e-acdb99db30c4
:END:
** connectedness in terms of 'touches' relation: { every cont. function from X ot (0, 1) is const }
:PROPERTIES:
:ID:       2eee5c1a-6b6e-4f80-8f84-291c84eeb0a3
:END:


* Compactness                                                      :topology:
:PROPERTIES:
:ID:       387a7c50ec72b225a6d578c5b4a60c34
:END:
** pdf by Tao compacness and compactification
:PROPERTIES:
:ID:       c4b5abad2e10daefc992170191d8d570
:END:
The extended real line is compact: any sequencexnof extended real numbers willhave a subsequence that either converges to +∞, converges to−∞, or convergesto a finite number. Thus by using this compactification of the real line, we cangeneralise the notion of a limit, by no longer requiring that the limit has to bea real number.
** TODO read synthetic topology of data types and classical spaces
:PROPERTIES:
:ID:       f83b9ba45f96e9d32e9132105b91da39
:END:


* [2016-08-14] ODE Integrating factor: y' + f(t) y = g(t)
:PROPERTIES:
:ID:       c3cf642b4d30a06347864cca0b196b32
:END:
- multiply both parts by e^{\int f(t) dt}
- after that, we have
  (y exp(\int f(t) dt)' = g(x) exp(\int f(t) dt)
  Easy to solve.

Homogenous: Sum_{n=0}^N A_n y^(n) = 0

- Guess: y = e^{z x}, then everything reduces to the polynomial:
- Replace derivative y^(n) with z^n, solve for z, get the solution.
- If multiplicity of root z is m, then: x^k e^zx for k from 0 to m-1
- Linear independence can be shown using Vandermonde determinant

* [2016-06-20] free structures                                      :algebra:
:PROPERTIES:
:ID:       9dfbc9b97cea18a4c20a0cbabe5af7e8
:END:
free monoids are lists
free semigroups are nonempty lists?
free magmas are nonempty binary trees (data is in lists)
* [2020-03-22] Shtetl-Optimized » Blog Archive » Ask Me Anything: Apocalypse Edition :math:
:PROPERTIES:
:ID:       02039b9e133528c97c188db6d0791c4f
:END:
https://www.scottaaronson.com/blog/?p=4684
Selection:
As a simple example, I’m totally fine uttering statements like, “a family of Boolean functions with superquadratic gap between randomized and quantum query complexities exists“—even though the type of “existence” that we’re talking about clearly isn’t physical (some would call it Platonic).
