#+TITLE: General topology
#+filetags: topology

* [2019-04-24] charts and atlases
** chart -- homeomorphism from an open subset of manifold to some other space (not necessarily eucledian generally)
** atlas -- collection of charts, covering the whole space
*** [2019-04-24] think of Earth as the space and atlas as a set of flat maps
** if codomain of atlas is eucledian, the space is a manifold
*** local chart for manifold introduces curvilinear coordinates (coming from eucledian space)
** [2019-04-24] https://en.wikipedia.org/wiki/Atlas_(topology)
One often desires more structure on a manifold than simply the topological structure. For example, if one would like an unambiguous notion of differentiation of functions on a manifold, then it is necessary to construct an atlas whose transition functions are differentiable. Such a manifold is called differentiable. Given a differentiable manifold, one can unambiguously define the notion of tangent vectors and then directional derivatives.

* [2019-04-24] identification of circles etc
** [2019-04-24] https://math.stackexchange.com/a/433969/15108 antipodal gluing of circle is circle again. nice gif
*** [2019-04-24] antipodal identification of circle (S^1) is [ circle ] :drill:
** [2019-04-24] identificaiton of 2D disk: right -- it's exactly the first diagram here! https://en.wikipedia.org/wiki/Real_projective_plane if you draw disk as a square.
*** [2019-04-24] this also kinda makes sense if you draw for a bit https://math.stackexchange.com/a/1391731/15108
*** [2019-04-24] antipodal identificaiton of disk (D^2) is [ RP^2 ] :drill:
*** [2019-04-24] https://mathcurve.com/surfaces.gb/planprojectif/planprojectif.shtml
Here are classic models of the projective plane: 
- The set of vectors of R^3 with the natural topology
- A (real affine) plane completed by a projective line (line at infinity)
- A sphere where the antipodal points are identified
- A closed disk where the antipodal points of the circumference are identified

* [2019-01-23] (2) Gluing a Sphere - YouTube             :topology:
https://www.youtube.com/watch?v=mmkreUEoGr8
Selection:
Often the fundamental group of the glued object can be calculated from the pieces (here two rectangles) and the glue (here a circle). The mathematical tool to do this is called the Seifert-van Kampen Theorem.

* [2019-01-23] Union of two simply connected open subsets with path-connected intersection is simply connected - Topospaces :topology:
https://topospaces.subwiki.org/wiki/Union_of_two_simply_connected_open_subsets_with_path-connected_intersection_is_simply_connected
Selection:
Both  and  are trivial, so we get  is an amalgamated free product of two trivial groups, hence it must be trivial.

* Data type topology                                               :topology:
** [2019-01-26] Infinite compact sets
https://perl.plover.com/classes/data-topology/samples/slide022.html
Selection:
 one-point compactification of ℕ
** [2019-01-26] Compactness
https://perl.plover.com/classes/data-topology/samples/slide021.html
Selection:
Compact set	=	Set that can be exhaustively searched
** [2019-01-26] Equality
https://perl.plover.com/classes/data-topology/samples/slide019.html
Selection:
Discrete space	=	Semidecidable equality
** [2019-01-26] Topology of Data Types
https://perl.plover.com/classes/data-topology/
** [2019-01-26] References and further reading
https://perl.plover.com/classes/data-topology/samples/slide027.html
Selection:
Other materials at http://www.cs.bham.ac.uk/~mhe/

* DONE [2019-01-26] A Logical Interpretation of Some Bits of Topology – XOR’s Hammer :logic:
- State "DONE"       from              TS!!
https://xorshammer.com/2011/07/09/a-logical-interpretation-of-some-bits-of-topology/
** [2019-04-24] mm, not sure how this can be useful now...

* TODO Tweet from John Carlos Baez (@johncarlosbaez), at Mar 16, 01:18
@zariskitopology So "compact" doesn't mean "small": it means "doesn't have any fuzzy edges".

https://twitter.com/johncarlosbaez/status/1106726463607209985



* TODO old zim notes

** [2016-06-18] compactness
- usual axioms of real numbers: forall a, b: a + b = b + a, forall x, y. exists z. x * z > y, so on
- add constant eps
  - infinite number of axioms for each n: eps < 1/n
  - eps > 0
for each finite subset of eps axioms there clearly is a model with \bbR
for infinite set: no model with \bbR as domain! Nonstandard real numbers, hyperreals

** [2016-06-20]  connectedness
Connected: can't be represented as a union of two disjoint open sets.
Locally connected at x: for every open V(x), there is connected open U(x) \subset V(x). X is locally connected if locally connected at every point.

Local connectedness and connectedness are unrelated!

Path connected: there is a path joining every pair of points.
Locally path connected at x: for every open V(x), there is connected open U(x) \subseteq V(x). X is locally path connected if locally path connected at every point.

Simply connected: path-connected and fundamental group is trivial.
Locally simply connected: admits a base of simply connected sets. Also locally path-connected and locally connected.


** [2015-06-14] Extracting topology from convergence

f_n -> weak(*) f if forall x. f_n(x) -> f(x)
How to develop intuition abut the open sets?

f_n converges weakly to f if it converges pointwise

f_n converges weakly to f:
forall O(f). exists N. forall n > N. f_n \in O

What is O? finite number of points do not converge? 
