#+TITLE: General topology
#+filetags: :math:topology:

* [2019-04-24] charts and atlases
:PROPERTIES:
:ID:       chrtsndtlss
:END:
** chart -- homeomorphism from an open subset of manifold to some other space (not necessarily eucledian generally)
:PROPERTIES:
:ID:       chrthmmrphsmfrmnpnsbstfmnthrspcntncssrlycldngnrlly
:END:
** atlas -- collection of charts, covering the whole space
:PROPERTIES:
:ID:       tlscllctnfchrtscvrngthwhlspc
:END:
*** [2019-04-24] think of Earth as the space and atlas as a set of flat maps
:PROPERTIES:
:ID:       thnkfrthsthspcndtlssstffltmps
:END:
** if codomain of atlas is eucledian, the space is a manifold
:PROPERTIES:
:ID:       fcdmnftlsscldnthspcsmnfld
:END:
*** local chart for manifold introduces curvilinear coordinates (coming from eucledian space)
:PROPERTIES:
:ID:       lclchrtfrmnfldntrdcscrvlnrcrdntscmngfrmcldnspc
:END:
** [2019-04-24] https://en.wikipedia.org/wiki/Atlas_(topology)
:PROPERTIES:
:ID:       snwkpdrgwktlstplgy
:END:
One often desires more structure on a manifold than simply the topological structure. For example, if one would like an unambiguous notion of differentiation of functions on a manifold, then it is necessary to construct an atlas whose transition functions are differentiable. Such a manifold is called differentiable. Given a differentiable manifold, one can unambiguously define the notion of tangent vectors and then directional derivatives.

* [2019-04-24] identification of circles etc
:PROPERTIES:
:ID:       dntfctnfcrclstc
:END:
** [2019-04-24] https://math.stackexchange.com/a/433969/15108 antipodal gluing of circle is circle again. nice gif
:PROPERTIES:
:ID:       smthstckxchngcmntpdlglngfcrclscrclgnncgf
:END:
*** [2019-04-24] antipodal identification of circle (S^1) is { circle } :drill:
:PROPERTIES:
:ID:       e3e6cc76-b4f0-4bce-8eee-3c331dfc14e8
:END:
** [2019-04-24] identificaiton of 2D disk: right -- it's exactly the first diagram here! https://en.wikipedia.org/wiki/Real_projective_plane if you draw disk as a square.
:PROPERTIES:
:ID:       dntfctnfddskrghttsxctlythwkrlprjctvplnfydrwdskssqr
:END:
*** [2019-04-24] this also kinda makes sense if you draw for a bit https://math.stackexchange.com/a/1391731/15108
:PROPERTIES:
:ID:       thslskndmkssnsfydrwfrbtsmthstckxchngcm
:END:
*** [2019-04-24] antipodal identificaiton of disk (D^2) is { RP^2 }   :drill:
:PROPERTIES:
:ID:       83c8678e-9913-4789-9652-9a0e9cf09e6a
:END:
*** [2019-04-24] https://mathcurve.com/surfaces.gb/planprojectif/planprojectif.shtml
:PROPERTIES:
:ID:       smthcrvcmsrfcsgbplnprjctfplnprjctfshtml
:END:
Here are classic models of the projective plane: 
- The set of vectors of R^3 with the natural topology
- A (real affine) plane completed by a projective line (line at infinity)
- A sphere where the antipodal points are identified
- A closed disk where the antipodal points of the circumference are identified

* [#C] [2019-01-23] (2) Gluing a Sphere - YouTube                  :topology:
:PROPERTIES:
:ID:       glngsphrytb
:END:
https://www.youtube.com/watch?v=mmkreUEoGr8
: Often the fundamental group of the glued object can be calculated from the pieces (here two rectangles) and the glue (here a circle). The mathematical tool to do this is called the Seifert-van Kampen Theorem.

* [#C] [2019-01-23] Union of two simply connected open subsets with path-connected intersection is simply connected - Topospaces :topology:
:PROPERTIES:
:ID:       nnftwsmplycnnctdpnsbstswtntrsctnssmplycnnctdtpspcs
:END:
https://topospaces.subwiki.org/wiki/Union_of_two_simply_connected_open_subsets_with_path-connected_intersection_is_simply_connected
: Both  and  are trivial, so we get  is an amalgamated free product of two trivial groups, hence it must be trivial.

* [#D] Data type topology                                          :topology:
:PROPERTIES:
:ID:       dttyptplgy
:END:
** [#C] [2019-01-26] Infinite compact sets
:PROPERTIES:
:ID:       nfntcmpctsts
:END:
https://perl.plover.com/classes/data-topology/samples/slide022.html
:  one-point compactification of ℕ
** [#C] [2019-01-26] Compactness
:PROPERTIES:
:ID:       cmpctnss
:END:
https://perl.plover.com/classes/data-topology/samples/slide021.html
: Compact set	=	Set that can be exhaustively searched
** [#C] [2019-01-26] Equality
:PROPERTIES:
:ID:       qlty
:END:
https://perl.plover.com/classes/data-topology/samples/slide019.html
: Discrete space	=	Semidecidable equality
** [#C] [2019-01-26] Topology of Data Types
:PROPERTIES:
:ID:       tplgyfdttyps
:END:
https://perl.plover.com/classes/data-topology/
** [#C] [2019-01-26] References and further reading
:PROPERTIES:
:ID:       rfrncsndfrthrrdng
:END:
https://perl.plover.com/classes/data-topology/samples/slide027.html
: Other materials at http://www.cs.bham.ac.uk/~mhe/

* DONE [#C] [2019-01-26] A Logical Interpretation of Some Bits of Topology – XOR’s Hammer :logic:
:PROPERTIES:
:ID:       lgclntrprttnfsmbtsftplgyxrshmmr
:END:
- State "DONE"       from              [2019-04-24]
https://xorshammer.com/2011/07/09/a-logical-interpretation-of-some-bits-of-topology/
** [2019-04-24] mm, not sure how this can be useful now...
:PROPERTIES:
:ID:       mmntsrhwthscnbsflnw
:END:

* TODO [#D] Tweet from John Carlos Baez (@johncarlosbaez), at Mar 16, 01:18
:PROPERTIES:
:CREATED:  [2019-03-16]
:ID:       twtfrmjhncrlsbzjhncrlsbztmr
:END:

@zariskitopology So "compact" doesn't mean "small": it means "doesn't have any fuzzy edges".

https://twitter.com/johncarlosbaez/status/1106726463607209985



* TODO [#C] old zim notes
:PROPERTIES:
:ID:       ldzmnts
:END:
** [2016-06-18] compactness
:PROPERTIES:
:ID:       cmpctnss
:END:
- usual axioms of real numbers: forall a, b: a + b = b + a, forall x, y. exists z. x * z > y, so on
- add constant eps
  - infinite number of axioms for each n: eps < 1/n
  - eps > 0
for each finite subset of eps axioms there clearly is a model with \bbR
for infinite set: no model with \bbR as domain! Nonstandard real numbers, hyperreals

** [2016-06-20]  connectedness
:PROPERTIES:
:ID:       cnnctdnss
:END:
Connected: can't be represented as a union of two disjoint open sets.
Locally connected at x: for every open V(x), there is connected open U(x) \subset V(x). X is locally connected if locally connected at every point.

Local connectedness and connectedness are unrelated!

Path connected: there is a path joining every pair of points.
Locally path connected at x: for every open V(x), there is connected open U(x) \subseteq V(x). X is locally path connected if locally path connected at every point.

Simply connected: path-connected and fundamental group is trivial.
Locally simply connected: admits a base of simply connected sets. Also locally path-connected and locally connected.


** [2015-06-14] Extracting topology from convergence
:PROPERTIES:
:ID:       xtrctngtplgyfrmcnvrgnc
:END:
f_n -> weak(*) f if forall x. f_n(x) -> f(x)
How to develop intuition abut the open sets?

f_n converges weakly to f if it converges pointwise

f_n converges weakly to f:
forall O(f). exists N. forall n > N. f_n \in O

What is O? finite number of points do not converge? 
* [2016-06-18] hausdorff spaces                                    :topology:
:PROPERTIES:
:ID:       hsdrffspcs
:END:
Hausdorff if any two points can be separated by neighborhoods (diagonal is closed in product topology).

Space X is Hausdorff iff its apartness map

\ne : X x X -> S
(x, y) -> { x \ne y }

is continuous


Space is discrete if every singleton is open (or if its diagonal is open)

Space is discrete iff its equality map

\eq : X x X -> S
(x, y) -> { x = y }

is continuous
* [#C] [2019-01-23] (2) bothmer - YouTube          :topology:viz:inspiration:
:PROPERTIES:
:ID:       bthmrytb
:END:
https://www.youtube.com/channel/UCngLGVygGfVo3pxsRzeCN_A
** [2019-02-24] some topology visualisations
:PROPERTIES:
:ID:       smtplgyvslstns
:END:

* [#D] [2019-01-23] Long line (topology) - Wikipedia
:PROPERTIES:
:ID:       lnglntplgywkpd
:END:
https://en.wikipedia.org/wiki/Long_line_(topology)

* [#D] [2019-01-23] N-sphere is simply connected for n greater than 1 - Topospaces
:PROPERTIES:
:ID:       nsphrssmplycnnctdfrngrtrthntpspcs
:END:
https://topospaces.subwiki.org/wiki/N-sphere_is_simply_connected_for_n_greater_than_1

* [2019-01-26] open set = semidecidable property             :drill:topology:
:PROPERTIES:
:ID:       a52b1e71-46be-413b-b2e3-e6f0da87e6c6
:END:
