#+TITLE: Building cool software projects
#+filetags: project

How to make good programming projects? Best practices in communicating and explaining, demos, presentations, etc.

* TODO [#C] [2019-08-18] Why not… — attrs 19.1.0 documentation :project:exobrain:
:PROPERTIES:
:ID:       3ab18b10e3aa918890e4e70a27b8505e
:END:
http://www.attrs.org/en/stable/why.html
Selection:
Why not…
* [#B] [2019-12-30] Choosing a license for GoatCounter              :license:
:PROPERTIES:
:ID:       48290315e7afbc6c0aa3e02efa229b0b
:END:
https://www.arp242.net/license.html
Selection:
GPL (any version)
Bad: doesn’t have the “network protection”: you don’t need to submit changes back to me if you modify the code and run it only as a SaaS.

* [#B] for end user software, calendar versioning is more useful than semantic
:PROPERTIES:
:CREATED:  [2020-01-02]
:ID:       4352347c2f5afdb8f243bc07ec98eec2
:END:


* [#B] [2020-01-19] How do you stay inline with your vision on long term projects? | Lobsters
:PROPERTIES:
:ID:       b78066cd8fcd9885216d58f1162c7cb6
:END:
https://lobste.rs/s/pg1ne9/how_do_you_stay_inline_with_your_vision_on#c_ihhrfy

* Demos/Screencasting
:PROPERTIES:
:ID:       53dd7295eb7a525d3043a118e8d1e2ba
:END:
** [2020-03-25] screenkey program to display keys                :screencast:
:PROPERTIES:
:ID:       0812e1869d992b764ee972f46d572c4f
:END:
** TODO [#B] [2019-12-10] [[https://reddit.com/r/coolgithubprojects/comments/e8pu54/github_asciinemaasciinema_terminal_session/][GitHub - asciinema/asciinema: Terminal session recorder 📹]] /r/coolgithubprojects :demo:screencast:
:PROPERTIES:
:ID:       2f45a74eb5135704829c0d687eb12125
:END:
** [2020-04-02] phw/peek: Simple animated GIF screen recorder with an easy to use interface
:PROPERTIES:
:ID:       c768531e93ee23307d9005b6f99c3c06
:END:
https://github.com/phw/peek#how-can-i-capture-mouse-clicks-andor-keystrokes
Selection:
Peek does not support this natively. But you could install an external tool like key-mon which is usually included in most distributions, so you can easily install with your package manager. Then start key-mon with key-mon --visible_click. The --visible_click option is for drawing small circles around mouse clicks.

** [2020-04-02] Capture/Desktop – FFmpeg                               :demo:
:PROPERTIES:
:ID:       dd62871d75cc6a44e7893687ca821c43
:END:
https://trac.ffmpeg.org/wiki/Capture/Desktop
** [2020-04-02] recordmyscreen                                        :demos:
:PROPERTIES:
:ID:       1a6c5f8aecb6f6f4a4a9c8144a18e0e1
:END:
I think it dumps broken ogv file. There is some jerkiness.
When you convert it to something else with ffmpeg, it's complaining about broken frames and sometimes even segfaults

also it hasn't been updated for a decade, apparently
** TODO [#B] [2019-10-11] [[https://reddit.com/r/orgmode/comments/dgeojs/weekly_rorgmode_open_discussion_october_11_2019/f3d7d0u/][Weekly /r/Orgmode Open Discussion - October 11, 2019]] /r/orgmode -- gif screencasting tool :blog:publish:demo:
:PROPERTIES:
:ID:       8ac291f2fed4b3a2897be56610408297
:END:
That looks really cool.  Note that many users don't know what CFEngine is, so you might want to mention that (then again, maybe users who don't already know what it is don't matter, haha).

Your demo GIF is pretty cool.  You might find this interesting: after recording and tidying up demo GIFs for `helm-org-ql` several times, I wrote a shell script to make it easier.  Using the `gif-screencast` package for Emacs, all I have to do is run the script, make the Emacs window active, and it does the rest.

https://github.com/alphapapa/org-ql/blob/master/images/demo-helm-org-ql.sh
** [#B] [2020-01-27] [[https://reddit.com/r/emacs/comments/eut02p/gifscreencast_11_is_out/][gif-screencast 1.1 is out]] /r/emacs :demo:emacs:
:PROPERTIES:
:ID:       94e32207bc8d8174dcc694ae9bd8ebfa
:END:
:  I'm happy to announce the release gif-screencast 1.1!
:  https://gitlab.com/ambrevar/emacs-gif-screencast
: 
:  It isn't much, but I know that gif-screencast has had annoying issues for a
:  while, I figured I'd rather let the community know!
: 
:  - Fix off-by-one error in frame delay (thanks to /u/alphapapa for this one!)
:  - Remove "Press ... to stop" message from resulting GIF.
:  - New `gif-screencast-start-or-stop` command.
:  - Log the complete command lines of all invokes commands.
