#+TITLE: 
#+filetags: quantum:gravity:lqg

* mc:/L/Dropbox/study/loop-quantum-gravity
** acm.pdf thing -- poses problem for computer scientists

* http://math.ucr.edu/home/baez/spacetime_from_spin/
pdf downloaded


* Very cool and insightful seminar notes (the categorical diagrams bit) http://math.ucr.edu/home/baez/QG.html

* http://math.ucr.edu/home/baez/nth_quantization.html
* START [#B] loop quantum gravity?..                          :simulation:qg:

** [2018-10-30]  https://github.com/joeydumont/wignerSymbols
  It reimplements the algorithm designed by Schulten and Gordon in C++, but also contains the original Fortran implementation. 
https://github.com/Jutho/WignerSymbols.jl


** [2018-10-30]  ok, so this is the interesting bit http://www.math.ucr.edu/home/baez/planck/node4.html
computing transition amplitudes for a certain cobordism between two space states
 They only happen because of the carefully chosen recipe for computing amplitudes for spacetime geometries. This recipe is the real core of the whole construction. Sadly, it is a bit too technical to describe here, so the reader will have to turn elsewhere for details [19,30]. I can say this, though: the reason this recipe works so well is that it neatly combines ideas from general relativity, quantum field theory, and a third subject that might at first seem unrelated -- higher-dimensional algebra.

* [2018-08-10] (23) Quantum Spin Dynamics in Loop Quantum Gravity - YouTube :qg:
https://www.youtube.com/watch?v=26PIHRRHGTo
* [2018-08-10] (23) Quantum Gravity Test simulation/ 3D Quantum hall (Triangular Heisenberg lattice system ) - YouTube :qg:
https://www.youtube.com/watch?v=lF6GqQ5QrJE
* think about loop quantum gravity and faster simulations! (baez)
