#+TITLE: Sleep tracking
#+filetags: :qs:sleep:
#+logseq_graph: false

* https://sleepjunkies.com/features/the-ultimate-guide-to-sleep-tracking/
:PROPERTIES:
:CREATED:  [2018-03-01]
:ID:       sslpjnkscmftrsthltmtgdtslptrckng
:END:

** TODO professional: PSG (polysomnography), which includes
:PROPERTIES:
:ID:       prfssnlpsgplysmngrphywhchnclds
:END:
- EEG
- EOG (oculogram)
- ECG
- EMG (myogram)
- oxygen levels
- air flow
- noise
- blood pressure
** typically, Fitbit, etc. misidentify wake as sleep and overestimage sleep time
:PROPERTIES:
:ID:       typcllyftbttcmsdntfywksslpndvrstmgslptm
:END:

* START Emfit QS
:PROPERTIES:
:ID:       mftqs
:END:
emfit -- bad reviews are just people not happy with price and EM radiaion
emfit qs -- needs website?
ok emfit qs and qs active are the samething apparently

script for getting data https://forum.quantifiedself.com/t/beddit-vs-emfit-qs/1606/8
https://biohackrrr.wordpress.com/2015/10/03/the-proper-way-of-tracking-your-sleep-thoughts-about-emfit-qs/


* TODO oura ring for hr? https://ouraring.com/
:PROPERTIES:
:ID:       rrngfrhrsrrngcm
:END:
  https://www.alexfergus.com/blog/the-one-wearable-to-rule-them-all-oura-ring-review
sergef promo code for 100$ discount

* TODO [#B] zmachine?? http://generalsleep.com/insight.html             :eeg:
:PROPERTIES:
:ID:       zmchngnrlslpcmnsghthtml
:END:
huh looks interesting. eeg apparently.  however only available for research?
shit, price starts and 499 gbp...

* TODO [#C] [2018-07-12] dreem band?                                    :eeg:
:PROPERTIES:
:ID:       drmbnd
:END:
Dreem is the closest thing I've seen. It's slick but it's a bit pricier than the Zeo, $500.
https://dreem.com/en/technology
https://www.reddit.com/r/Biohackers/comments/8dn6tw/dreem_headband_initial_thoughts/
eh, 499 usd??
** eeg, accelerometer, breathing, pulse oxymeter
:PROPERTIES:
:ID:       gcclrmtrbrthngplsxymtr
:END:
** https://blog.dreem.com/en/meditate-with-dreem-and-fall-asleep-more-easily/ hmmm
:PROPERTIES:
:ID:       sblgdrmcmnmdttwthdrmndfllslpmrslyhmmm
:END:

** eh, mixed reviews
:PROPERTIES:
:ID:       hmxdrvws
:END:
https://gizmodo.com/this-smart-headband-was-supposed-to-help-me-sleep-bette-1822568894 this one is quite bitter
* CANCEL ResMed S + monitor
:PROPERTIES:
:ID:       rsmdsmntr
:END:
http://wheresmycreditcard.com/s-resmed-personal-sleep-solution/
err.. contactless so how the fuck it detects hr??? https://www.resmed.com/us/en/consumer/s-plus.html
https://www.reddit.com/r/sleep/comments/5vyg0u/resmed_s_vs_beddit_30/

* CANCEL beddit -- works by ballistography
:PROPERTIES:
:ID:       bddtwrksbybllstgrphy
:END:
Accessing the Raw Data
Beddit has a feature to download raw data to a spreadsheet, which can be very useful for doing any detailed analysis. It even gives more advanced metrics like overnight Heart Rate Variability (HRV).

Beddit also has an API to access data, but currently only available for companies or research teams.

Compared to high-end sensors on the market (Emfit QS, ResMed S+), the Beddit stands up well.

* CANCEL Withings Aura -- apparently old version of nokia sleep
:PROPERTIES:
:ID:       wthngsrpprntlyldvrsnfnkslp
:END:
* CANCEL Sense -- shut down
:PROPERTIES:
:ID:       snsshtdwn
:END:
* CANCEL zeo -- went bust..                                             :eeg:
:PROPERTIES:
:ID:       zwntbst
:END:
I wish ResMed would make a new one. They bought up all the intellectual property from Zeo. Instead, they put out their useless contactless tracker and sat on the Zeo tech.
I use the Zeo mobile. You can still find it and the larger units on ebay.

* CNCL [#B] buy jawbone again? at least it measured something... :jawbone:qs:
:PROPERTIES:
:CREATED:  [2018-03-01]
:ID:       byjwbngntlsttmsrdsmthng
:END:

right, jawbone is liquidating, so guess not worth buying now
jawbone3 didn't even connect to my phone properly
nokia sleep? (igor shilov)
maybe beddit? Can't find good reviews though.

deck size 30-32 inches for surf training, versatile
